<?php
$arr_evt=array("Ballyhoo","Premier League","Contingency","Boulevard","Subterfuge","Lockout","Quid Pro Quo","Board Room","Freakonomics","Indemnity","Builder","Stock Exchange","Linking Pin");

$arr_rules=array("No. of Participants: 2  \nDuration: 4+3 minutes (3 minutes the for questioning)
\nRULES:
●	Each school shall represent the PR agents of a given firm or individual.
●	No school shall exceed the time limit of four minutes.
●	Each school will be given the crisis on spot by lottery, and the participants shall come up with solutions and do their best to defend and restore the public image of the firm.
●	The participants shall be asked questions by the judges as well as the board and other participants at the end of their defence.
●	Participants will be marked on how they protect the image of the firm, the impact on the sales, and provide measures for future prevention of such situation.
●	Use of unparliamentary language is strictly prohibited and shall lead to disqualification.",
"No. of Participants: 3 \nDuration: 2 hours 
\nRULES:
•	Every school will be provided with a cricket team consisting of 11 players, each having a specific book value.
•	Schools have to sell 4 of their players so as to generate a purse which will henceforth be used for the auction.
The players that are sold by all schools will be the players who go under the hammer.
•	Each school has to purchase exactly 4 players from the pool, from the proceeds generated by the sale of the four players.
•	After every 10 players are sold there will be a 5 minutes trade round between schools.
•	At the end of the event, schools will be required to defend their decisions of selling their players and explain how the team is stronger than it was before.
•	Every school should prefer sending at least one participant who has knowledge in the field of cricket.
•	Decisions to sell will be valued at Market Value (Purchase price of player during auction) - Book Value (Sale price of player before auction)
•	If the book value is greater than the market value, the difference will be the value of loss. If market value is higher, difference will be value of profit.
•	A team cannot have more than 11 players at the end of the auction.",
"No. of Participants: 2
\nDuration: 5+1 minutes

\nRULES:
●	Each participating school will assume the role of a Management Consulting Firm.
●	The participants are required to present solutions to a business case based on their clients which must be presented in the form of a presentation, not exceeding 6 minutes, after which, the participants will be subject to questioning by the judges.
●	The presentation must contain realistic solutions backed by evidence and estimates of their effectiveness and accuracy. The implementation process of the business strategy to overcome the problem/problems should be clearly shown and explained. Financial estimates and statistics will be looked favourably upon.
●	Long-term advice must also be provided for the business to overcome or avoid the problem in the future.
●	The crises will be given to the schools a day prior to the event.",
"No. of Participants: 3 \nDuration: 2 hours 
\nRULES FOR ROUND 1: 
●	Each participating school will be given a company one hour prior to the event. They will have to pair up with another participating school's company and present a joint venture presentation (Subject to Questioning). 
●	Each pair of school will get 5+2 minutes to present and explain their joint venture. They will also have to put up their presentation during this time period. 
\nRULES FOR ROUND 2:
●	The top 2 pair of schools (top 4 schools) will qualify for round two. These schools will be given another company and they will have to pitch a joint venture with the company given to them in the first round.
●	Each school will be given 4 minutes in which they will have to present their ideas verbally.  ",
"No. of Participants: 3 
\nDuration: 120 Minutes

\nRULES:
●	Each school will be allotted a company a day before the event. 
●	The participants are expected to come up with a new product which they will have to market on the day of the event along with a presentation of maximum 3 minutes. 
●	After all the schools have presented their product, they will be grouped into pairs from the same sector. 
●	Each group shall be given 30 minutes to analyse the opponent company and market their product through Ambush Marketing. 
●	Participants should not directly refer to their opponents. 
●	No personal references should be made by any participants. Any such reference shall lead to immediate disqualification. ",
"No. of Participants: 2
\nDuration:  5 minutes

\nRULES:
●	This event will consist of an impromptu human resource crisis which will be given by a staff member from the organization.
●	After this, there will be a negotiation round on stage between the human resource team and the staff member.
●	The participant represents the human resource manager who has to negotiate with the staff to convince them to put an end to the said crisis.
●	The participants shall be judged on the basis of their negotiation skill and their ability to judge the situation with a good presence of mind.",
"No. of Participants: 2
\nDuration: 3 hours

\nGENERAL RULES:
●	Each participating school will send two participants for this event.
●	This event tests the legal and business acumen of the participants through negotiation sessions and moot courts based on corporate law.
●	The factors determining the winning side in the first round will be the skills of negotiation, manipulation, persuasion and passive coercion. The terms of the deal decide the winner, not the oratory skills, where each team, being a party to a deal/conflict will try to negotiate a deal with the other party, represented by the organizers.  
●	The second round will follow modified moot court procedure followed around the world, with each team being given a trial court case instead of the standard appellate case.
●	Only the top 4 teams will qualify for the second round. 

ROUND 1:
●	The first round is a Negotiation round, based on Alternative Dispute Resolution (ADR), wherein each participating team represents their client and negotiates on their behalf to resolve a dispute or form a deal/agreement.
●	This round will be between the organisers and the various participants, as in, each case, the organizing team will represent one party while the participating team will represent the other.
●	The negotiation will be based on some common facts and different confidential information privy to each side.
●	Role allocation shall be made clear within each problem.
●	Creation of extraneous facts is not permitted, and teams shall be penalized for the same.
●	The general set of facts shall be released to the participants 20 minutes in advance, as well as the party each team represents.
●	Each session will last for not more than 10-15 minutes, at the end of which, the signed deal will have to be handed over to the judge, who will have witnessed the negotiation.

ROUND 2:
●	This round will be a moot court based on corporate law.
●	The top 4 schools from round 1 qualify for the second round.
●	The round will take place on the basis of reverse power allocation (the qualified teams will be ranked), i.e. Team 1 vs Team 4, Team 2 vs Team 3.
●	The participants will be given 20 minutes of preparation time, during which they can make use of the internet.
●	The two paired schools will be allotted a case (lawsuit), each team representing the plaintiff or the defendant, based on lottery.
●	The facts of the case will be provided at the beginning of the preparation time. 
●	Unlike moot courts at law school, no memorial/case brief has to be submitted by either team.
●	All cases will be lawsuits dealing with corporate law. They may be actual cases that have been recreated or fictional ones. 
●	Use of precedents is highly encouraged. 
●	As per standard procedure, the counsels will be subject to questioning by the judge during the course of their arguments. 
●	Each speaker gets 5 minutes to speak.  
●	No verdict will be given. Instead, the winning team will be declared by the judge. The two winning teams proceed to the final and follow the same format to decide the winner.",
"No. of Participants: 7
\nDuration: 6+12 minutes

\nRULES:
●	All schools shall represent a department of the same company.
●	A detailed report about the company as a whole (strengths and weaknesses) shall be given to the participating schools 20 minutes prior to the event. The departments shall be allotted via a lottery system.
●	The participants of every school will have to discuss the solutions to the problem faced by its department and overall problems faced by the company and will subsequently be told to go on stage to pitch their solution. 
●	On their way to the stage, they will be given another crisis pertinent to their department.
●	The participants will again get another 10 minutes on stage to discuss the new crisis and find solutions to it.
●	The concerned Head of Department (to be chosen by the participants of the respective school by themselves) will come and give a summary of their discussion to the shareholders of the company.
●	The shareholders shall question the participants on the basis of what they have proposed.
●	The judges shall monitor the entire proceedings and will mark the participants on all of the above aspects.",
"No. of Participants: 2
\nDuration: 4 Hours

\nRULES:
●	Every school will be sending two participants, one will represent the producer and the other the buyer.
●	The producer will be producing two types of products (say, A and B). He will be demanding raw materials and labourers which will be supplied to him by the open market and machinery from the buyer. (A and B will be produced from raw materials in a given proportion.)
●	The buyer will be demanding products A and B from the producer, supplying machinery to the same and will be selling products in the open market.
●	The producer will be having sufficient cash in the beginning and the buyer will have minimal cash and a specified number of machineries.
●	An exact number of labourers will be required to operate the machinery. The maximum output from a machine will be stated. Labourers need to be paid wages every round whether or not they are employed. 
●	Raw materials will be supplied in any quantity and the prices of raw materials will remain constant.
●	The prices of products and machinery will fluctuate every round on the basis of difference between demand and supply.
●	There shall be negotiation rounds in between two rounds of trading and trade agreements may take place.
●	At last, the stock of machinery, products, raw materials will be liquidated and the participants with the highest liquid cash balance will be declared winner.
●	Participants are expected to bring their own calculators.
●	An orientation shall be conducted before the event to further clarify the event.",
"No. of Participants: 2
\nDuration:  6 minutes

\nRULES: 
●	The participating schools will be given a comprehensive report of an incident that has occurred and the damage that has been done to their insured commodity/commodities.
●	The terms and conditions of the insurance policy will be provided.
●	The participants have to negotiate with the judges (insurance company) and obtain the maximum percentage of the loss from the insurance company.",
"No. of participants: 3
\nDuration: 3 hours

\nRULES:
\●	The first round would be an open auction for the different sectors of an economy where the participants would have to build a start-up. A comprehensive report of the economy would be provided.
●	To acquire funds for the auction, the participants would have to go through a series of tests.
●	Participants must, in the second round, pitch their start up based on only one particular sector. 
●	After having acquired a particular sector, the participants must build a start-up and pitch their ideas to the sharks keeping in mind the given situation of the economy.
●	In the second round, they will have to pitch their start up idea within 3-4 minutes.
●	A visual presentation (by means of PowerPoint, Video or Graphics) supporting the pitch will be required.
●	Following the start-up pitch, the participating schools will have to seek investment for their start up from the investors present.
●	They will be given a further 2+1 minutes to convince the investors to invest in their company/venture.
●	The schools may come up with a suitable valuation of their company which will be based on these factors:
  	i) Revenue / Sales Model
  	ii) Traction
  	iii) Market Share
  	iv) Distribution Channel
   	v) Cost structure
Note: It is to be kept in mind that the firm is considered to have no sales when seeking the investment.
●	The schools are requested to come up with a very practical and sensible valuation of the company as it might be questioned by the investors.
●	Further details shall be disclosed on the day of the event.  ",
"No. of Participants: 1  \nDuration: Throughout the 2 Days of the conclave.  
\nRULES:
●	Bosco Stock Exchange will serve as the scoreboard for Bosco Empresarios 2018. Each school has unlimited number of shares which are put to sale and which they can purchase via the BSE. The opening share prices of all the schools will be fixed at ₹ 100.
●	Each school is given a seed capital of ₹ 30 lakhs. Out of this fixed amount, ₹ 10 lakh has to be invested in its own shares. This amount cannot be increased or decreased. It can be encashed only at the end of the event.
●	The schools are free to invest in the shares of the other schools. Investment in the range of ₹ 2.5 lakhs to ₹ 5 lakhs can be made only in one school. Further investment in the shares of other schools cannot exceed ₹ 2.5 lakhs.
●	Buying and selling of the shares done by the participant of the school, known as the investor, will be based on speculation. Share prices after every event will increase or decrease based on the results of the events as decided by the judges. For example, if school X has its share prices at ₹100 and it stands 1st in an event, then after this event, its share prices will be ₹ 110. Similarly, if school Y comes second in the event, its share prices rises by ₹ 8 and becomes ₹ 108. If a school happens to be among those at the bottom half of the event (for example, in the bottom 5 if 10 schools are participating), then the share prices of the school shall fall. 
●	There can be a change in the share prices during an event as well. This will be done by four speculators, namely, the bull, the bear, the sheep, and the hawk. These speculators will be changing the share prices of the various schools after the performance of every school in the event. It is the job of the investor to speculate and take necessary action based on the price fluctuation made by the speculators. For example, if school X performs first and after its performance, the speculator feels that no other school can perform better, so he increases the price of the share of that school, say by ₹ 6. Another school comes up and performs better than the previous one, the speculator can increase its share prices to ₹ 108. All of this is taking place after every performance. At the end, when the judges announce the results, if school X comes first, hence its share prices should have increased from ₹ 100 to ₹ 110. But during the event, the speculator had already increased the prices by ₹ 8, then there will only be an increase in the price by ₹ 2 to make the share price ₹ 110. Suppose school X had come last in the event and its share prices should have decreased to ₹ 90 from ₹ 100 but the share prices after its performance were increased to ₹ 108 by the speculator, there will be a net decrease of ₹18 in the share prices of that school at the end of that event. 
●	Buying and selling of shares will be done only with the market. For any transaction to take place, all formalities will have to be completed by the investor at the Bosco Stock Exchange.
●	The fluctuations in the share prices will NOT be dependent on the theory of demand and supply. It will only depend on the performance of the schools, the speculation made by the speculators and the result given by the judges. The investors need to keep in mind all these factors while making any transaction with the market. A minimum of 8 transactions have to be carried out on day 1 and 3 transactions on day 2.
●	There will also be an option available to the investors to invest in a fixed deposit. The amount invested can only be encashed at the end of the event. The rate of return will be 3.0% per hour. A maximum of ₹ 5 lakhs can be invested under the fixed deposit scheme.
●	At the end of day 2, all the shares will be assumed as sold. The school making maximum profit on investment will be the winner of BSE.

NOTE: The weightage given to this event is going to be 1.5 times that of any other event, that is, if winning any other event results in an increase of the share price by ₹ 10, winning BSE will result in an increase of ₹ 15 in the share price.",
"Number of participant(s): 1
\nDuration: 45 mins for auction, 5 mins for pitch

\nRULES:
●	The event will consist of two rounds:
(a)	Auction (through closed bids)
(b)	Pitch
●	The participants will have to showcase their lobbying as well as networking skills in the event.
●	Participants, on the basis of their analysis and decision-making abilities, will have to come together to form an efficient supply chain.
●	Further details regarding the particular event shall be disclosed on the final day.
●	The participants must carry a smartphone or a laptop with an active internet connection for this event.");

$id = $_GET['id'];
global $event;
global $rules;
$event = $arr_evt[$id];
$rules = nl2br($arr_rules[$id]);
/**
$myfile = fopen("rules.txt", "r") or die("Unable to load rules!");
$event_rules=fread($myfile,filesize("rules.txt"));
fclose($myfile);


for($i=0;$i<strlen($event_rules);$i++){
    $x = strpos($event_rules,$i);
    if($x!=' ')
        $word= $word + $x;
    else{
        if(strcomp($word,$eventfirst)==0){

        }
    }

}**/
?>



<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from slimhamdi.net/bayya/about.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Oct 2018 07:18:21 GMT -->
<head>

    <meta charset="utf-8" />
    <title>Event Rules</title>
    <meta name="theme-color" content="#fd961a">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.png">

    <!-- Template CSS Files -->
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/select2.min.css">
    <link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/skins/orange.css">
	
	<!-- Live Style Switcher - demo only -->
    <link rel="alternate stylesheet" type="text/css" title="orange" href="css/skins/orange.css" /> 

    <!-- Template JS Files -->
    <script src="js/modernizr.js"></script>

</head>

<body>
    <!-- SVG Preloader Starts -->
    <div id="preloader">
        <div id="preloader-content">
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 612 792" style="enable-background:new 0 0 612 792;" xml:space="preserve">
                <g>
                    <path class="path" d="M307.2,475.3c-18.9,0-37.7,0-56.6,0c-2.8,0-5.5-0.3-8.2-1c-5.8-1.6-10.2-5.1-13.7-9.8
                        c-2.5-3.4-4.2-7.2-5.6-11.2c-0.9-2.7-1.6-5.5-1.9-8.4c-0.6-7.4-1.4-14.7-1.8-22.1c-0.7-13.7-3.2-27.1-6.7-40.4
                        c-5.1-19.8-12-38.9-19.8-57.8c-8.9-21.7-19.1-42.9-29.7-63.8c-3.5-7-7.4-13.8-10.4-21c-5.5-13.3-9.4-27-11.4-41.3
                        c-1.4-9.9-2-19.8-1.6-29.7c1.8-43.1,17.6-80.4,47.7-111.4c21.7-22.3,47.7-37.4,77.9-45.2c14.8-3.8,29.9-5.4,45.2-5.2
                        c71.1,1.1,133.7,48.1,155.7,114.5c4,12.2,6.6,24.7,7.8,37.5c1.1,11.6,0.9,23.2-0.4,34.7c-2.4,22.3-9.2,43.3-19.8,63
                        c-14.6,27.2-27.6,55.2-38.6,84c-6.1,16-11.3,32.2-15.2,48.9c-2.3,9.8-3.9,19.7-4.8,29.7c-0.1,1.1-0.2,2.2-0.2,3.3
                        c0,7-1.1,13.8-1.7,20.8c-0.3,3.2-0.6,6.4-1.6,9.4c-1.2,3.7-2.7,7.2-4.9,10.5c-5.3,7.9-12.7,12-22.3,12
                        C345.6,475.4,326.4,475.3,307.2,475.3z M338.4,343c-8.1,1.7-16.3,3.6-24.5,5.7c0,0.8,0,1.4,0,2.1c0.2,2.8,0.4,5.5,0.5,8.3
                        c0.5,15.9,1,31.8,1.3,47.6c0.3,16.3,0.2,32.7,0.3,49c0,1.1,0.1,2.2,0.2,3.4c1,0.1,1.9,0.2,2.7,0.2c5.5,0,11,0,16.6,0
                        c9.7,0,19.4-0.1,29.1,0c4.6,0,7.8-2,9.9-5.9c1.6-2.9,2.7-6,2.9-9.4c0.1-1.3,0.3-2.6,0.4-4c0.5-5.8,1.2-11.6,1.4-17.5
                        c0.4-10.1,1.8-20,3.9-29.8c3.1-15.2,7.5-30.1,12.6-44.8c11.8-33.8,26.7-66.2,43.6-97.7c11.2-20.8,18.1-42.8,19.2-66.4
                        c0.3-7.3,0.5-14.5-0.1-21.8c-1-11.9-3.3-23.6-7.1-34.9C432.6,70.5,380.3,26.9,315.4,23.3c-14.7-0.8-29.3,0.5-43.7,4
                        c-42.8,10.4-79.1,39.1-99.2,78.3c-9.9,19.4-15.4,40-16.4,61.8c-0.3,5.5,0.1,11,0.3,16.5c0.1,3.2,0.3,6.4,0.7,9.6
                        c1.8,13.9,5.3,27.2,10.8,40.1c2.9,6.9,6.5,13.5,9.9,20.2c13.3,25.7,25.5,51.8,35.8,78.8c8.1,21.1,15,42.6,19.1,64.9
                        c1.7,9.2,2.8,18.5,3,27.9c0,1,0,2,0.1,3c0.5,4.8,1,9.7,1.4,14.5c0.4,3.8,1.5,7.3,3.4,10.6c2.1,3.8,5.3,5.7,9.7,5.7
                        c15.8-0.1,31.6,0,47.3,0c0.7,0,1.4-0.2,2.2-0.3c0-1.2,0-2.2,0-3.2c-0.1-7.5-0.2-15-0.1-22.5c0.1-14.7,0.3-29.3,0.6-44
                        c0.2-11.6,0.4-23.2-0.2-34.7c0-0.7-0.2-1.5-0.3-2.3c-0.8,0.1-1.5,0.1-2.1,0.3c-9.2,2.2-18.5,4.1-27.9,5.4
                        c-6.5,0.9-12.9,1.4-19.5,0.9c-4.9-0.3-9.6-1.3-13.9-3.7c-7.3-4-11.2-10.3-11.3-18.5c-0.1-9.8,3.2-18.4,9.5-25.8
                        c4.5-5.3,10.3-8.1,17.2-9c4.7-0.6,9.2,0,13.7,1.3c6.1,1.7,11.7,4.5,17.1,7.8c7.3,4.5,13.9,9.8,20.2,15.5c1,0.9,2,1.7,3.1,2.4
                        c2.6,1.6,4.7,3.7,6.3,6.2c0.4,0.6,0.9,1.2,1.3,1.8c2-0.4,3.8-0.8,5.6-1.2c1.7-0.4,3.5-0.7,5.1-1.2c1.7-0.5,3.6-0.5,5.3-1.5
                        c-0.2-0.4-0.4-0.7-0.6-1c-4.2-5.6-8.3-11.2-12.5-16.7c-3.7-4.8-7.6-9.5-11.4-14.2c-20.3-25.3-40.5-50.7-60.8-76
                        c-1-1.3-1.6-2.5-1.5-4.2c0.1-4.7,0-9.5,0-14.2c0-0.6,0.1-1.3,0.1-2.1c3.1,0.1,6.1,0.3,9,0.3c10.6,0.3,21.2-0.5,31.4-3.5
                        c6-1.7,11.6-4.2,16.5-8.1c6.3-4.8,10.3-11.1,12-18.9c0.5-2.1,0.8-4.3,0.7-6.6c-1.3-0.3-2.5-0.2-3.7-0.2c-23,0-45.9,0-68.9,0
                        c-0.6,0-1.1,0-1.7,0c-0.6-0.1-1.3,0.3-1.9-0.6c4.1-6.1,8.2-12.4,12.3-18.6c1.1,0,1.9,0,2.8,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0
                        c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0
                        c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0
                        c0.9,0,1.8,0,2.6,0c1,0,2,0,3,0c0.8,0,1.7,0.1,2.7-0.3c-0.3-0.7-0.4-1.2-0.6-1.7c-1.8-4-4.6-7.2-8.1-9.9c-4-3.1-8.4-5.2-13.2-6.6
                        c-6.2-1.8-12.5-2.6-18.9-2.7c-10.5,0-21,0-31.4,0c-0.8,0-1.7,0.1-2.5-0.1c0-0.4-0.1-0.7,0-0.8c4.2-6.3,8.5-12.6,12.8-19
                        c42.9,0,85.7,0,128.5,0c0.3,0,0.6,0.2,1.2,0.4c-4.4,6.7-8.6,13.2-12.9,19.7c-1.2,0-2.3,0-3.4,0c-9.9-0.2-19.9-0.4-29.8-0.6
                        c-0.6,0-1.3-0.4-1.7,0.5c0,0.1,0,0.2,0.1,0.3c0.2,0.4,0.5,0.7,0.8,1.1c4.3,5.5,7.6,11.6,9.2,18.5c0.1,0.5,0.4,1,0.7,1.6
                        c1.7,0,3.2,0,4.7,0c9.7,0,19.4-0.1,29.1,0c0.7,0,1.5-0.5,2.2,0.6c-4,6.1-8,12.3-12,18.5c-2.7,0-5.4,0-8,0c-2.8,0-5.5,0-8.3,0
                        c-2.6,0-5.3-0.2-7.9,0.2c-0.4,1.7-0.7,3.3-1.1,4.9c-2.8,11-8.5,20.3-16.8,27.9c-7.5,6.9-16.4,11.5-26,14.7
                        c-7.1,2.3-14.3,3.6-21.6,4.5c-0.5,0.1-1.1-0.1-1.5,0.8c0.4,0.8,0.9,1.8,1.5,2.7c15.3,25.9,30.6,51.8,45.9,77.7
                        c2.4,4,4.8,7.9,7.6,11.6c4.2,5.3,8.3,10.6,12.4,15.9c0.5,0.7,1.1,1.4,1.5,1.9c2.3-0.4,4.1-0.7,5.9-1c5.9-0.9,11.8-1.5,17.8-1
                        c2.1,0.2,4.1,0.6,6.1,1.3c3.7,1.2,6.3,4.2,6,8.8c-0.2,3.2-0.7,6.4-1.2,9.5c-0.5,3.2-1.5,6.2-3.2,9c-2.3,3.6-5.5,5.3-9.8,4.6
                        c-1.4-0.2-2.8-0.6-4.1-1.2c-2.4-1.2-4.7-2.4-6.9-3.9c-3.7-2.5-6.9-5.5-10.1-8.6C341.9,346.3,340.3,344.8,338.4,343z M299.8,340
                        c-1.2-1.7-2.5-2.4-3.4-3.4c-3.4-3.9-7.6-7.1-11.7-10.2c-4.8-3.7-9.9-7-15.4-9.6c-3.3-1.6-6.7-2.8-10.3-3.4
                        c-6.9-1.1-12.7,0.7-16.9,6.5c-3.2,4.5-5.1,9.6-5.4,15.1c-0.3,5.1,1.9,8.4,6.2,10.3c2,0.9,4.2,1.4,6.4,1.7
                        c5.6,0.8,11.2,0.3,16.8-0.4c7.1-0.8,14.1-2.2,21.2-3.7C291.2,342,295.1,341.1,299.8,340z M365,349.6c1.3-3.1,1.9-6.2,1.9-9.3
                        c-3.5-1-10.3-0.7-13.5,0.5C355.8,344,360.6,347.7,365,349.6z"/>
                    <path class="path" d="M368.3,510.1c7.7,2.8,11.7,7.7,11.6,14.3c0,6.6-4,11.4-11.9,14.3c1.1,0.5,2,0.8,2.9,1.2c4.3,1.9,7.2,5,8.5,9.5
                        c2,6.7-1.6,14.3-8.9,17.1c-1.3,0.5-2.8,0.7-4.2,0.9c-1.2,0.2-2.4,0.1-3.6,0.1c-36.8,0-73.7,0-110.5,0c-1.2,0-2.4,0-3.6,0
                        c-6.6-0.4-12.3-5.4-13.4-11.7c-1.1-6.6,2.2-12.9,8.4-15.7c1-0.4,2-0.8,3.5-1.4c-4.4-1.2-7.8-3.3-10-6.8c-1.6-2.6-2.3-5.5-2.1-8.5
                        c0.4-6.2,4.5-10.9,12-13.2c-1.2-0.5-2.2-0.9-3.2-1.3c-5.6-2.6-8.7-6.9-8.8-13.2c-0.2-6.6,5-13.4,13-14.3c1.1-0.1,2.2-0.1,3.3-0.1
                        c37.4,0,74.8,0,112.2,0c2.1,0,4.2,0,6.2,0.7c5.8,1.9,9.9,6.9,10.3,12.9c0.3,5.8-3,11.5-8.8,13.9c-0.9,0.4-1.8,0.8-2.7,1.2
                        C368.4,509.9,368.3,510,368.3,510.1z M307.6,516.3c13.9,0,27.8,0,41.7,0c1.3,0,2.7-0.1,3.9-0.4c3.5-0.9,5.8-3.9,5.9-7.5
                        c0.1-3.8-2.1-6.9-5.7-7.9c-1.4-0.4-2.8-0.4-4.2-0.5c-27.8,0-55.6,0-83.4,0c-0.8,0-1.5,0-2.3,0c-4.4,0.4-7.7,3.9-7.7,8.1
                        c0,4.2,3.2,7.7,7.6,8.2c1,0.1,2,0,3,0C280,516.3,293.8,516.3,307.6,516.3z M297,548.8c9.9,0,19.8,0,29.7,0c1,0,2,0.1,3-0.1
                        c4-0.5,7.1-3.8,7.2-7.8c0.2-3.9-2.5-7.3-6.3-8.2c-1-0.2-2-0.3-2.9-0.3c-20.4,0-40.8,0-61.1,0c-1.1,0-2.2,0.1-3.3,0.4
                        c-3.6,0.9-6.1,4-6.1,7.7c-0.1,3.6,2.3,6.9,5.9,7.9c1.2,0.3,2.6,0.4,3.9,0.4C277,548.8,287,548.8,297,548.8z"/>
                    <path class="path" d="M353.2,573.3c-22.2,30.8-69.4,30.9-91.4,0.3c0-0.1,0-0.2,0.1-0.3c0.1-0.1,0.2-0.1,0.3-0.1
                        c29.8,0,59.5,0,89.3-0.1C352,573.2,352.4,573.3,353.2,573.3z"/>
                    <path class="path" d="M578,733.9c0.6,0.5,1.2,1,1.7,1.5c4.3,3.6,5.8,8.3,4.7,13.6c-1.1,5.2-4.6,8.4-9.5,10
                        c-4.7,1.5-9.4,1.3-13.9-0.4c-7-2.7-10.3-9.5-8.2-16.6c0.7-2.4,2.1-4.4,3.9-6c0.7-0.7,1.5-1.3,2.3-2c-0.8-0.9-1.5-1.7-2.3-2.5
                        c-6.4-6.9-3-17.7,5.9-20.4c4.1-1.2,8.3-1.2,12.4,0.2c8.4,2.8,11.3,12.6,5.8,19.6C580,731.9,579,732.8,578,733.9z M568.4,738.3
                        c-2.8,0-5.8,2.6-5.8,6.4c0,3.4,3.3,6.3,6.1,6.1c3.2-0.2,5.9-3,5.9-6.4C574.5,741.1,571.7,738.2,568.4,738.3z M573.6,724.4
                        c0.1-3-2.1-5.4-5-5.4c-2.8,0-5,2.1-5.1,4.9c-0.1,2.8,2.1,5.1,4.8,5.2C571.2,729.2,573.6,727.1,573.6,724.4z"/>
                    <path class="path" d="M467.4,735.4c-0.2-4.2,0.3-8.3,1.8-12.3c1-2.7,2.5-5.1,4.3-7.3c6.4-7.5,19.3-7,25.3-0.1
                        c2.9,3.2,4.6,7,5.4,11.1c1.2,6.1,1,12.3-0.5,18.3c-1.2,4.5-3.6,8.2-7.2,11.1c-7.1,5.6-17.7,4.5-23.5-2.3c-3.5-4.1-5.2-8.9-5.6-14.2
                        C467.3,738.3,467.4,736.9,467.4,735.4z M477.4,735.1c0,1-0.1,2,0,3c0.3,3.1,0.9,6.1,2.6,8.8c3.3,5.1,9.2,5,12.4-0.1
                        c1.2-1.9,1.8-4,2.2-6.2c0.6-3.6,0.5-7.3-0.1-10.9c-0.4-2.7-1.3-5.4-3.2-7.5c-2.7-3.1-7-3.2-9.9-0.3c-1.3,1.3-2.1,2.8-2.7,4.5
                        C477.8,729.1,477.4,732.1,477.4,735.1z"/>
                    <path class="path" d="M130.9,670.8c1.3,1.4,2.6,2.5,3.5,3.9c3.5,5.2,4,10.7,1.3,16.3c-2.7,5.7-7.5,8.5-13.8,8.6
                        c-6.7,0.1-13.5,0-20.2,0c-0.3,0-0.6-0.1-1.1-0.2c-0.1-0.7-0.2-1.5-0.2-2.3c-0.3-22.2-0.2-49,0.3-52c0.4-0.1,0.8-0.2,1.2-0.2
                        c6.4,0,12.8,0,19.2,0c8.1,0,12.9,5.8,14.2,11.2c1.1,4.5,0.1,8.5-2.5,12.2C132.3,669.2,131.6,669.9,130.9,670.8z M106.6,693.6
                        c5.4,0,10.5,0,15.7,0c0.4,0,0.9-0.1,1.3-0.1c4.2-0.5,7.4-3.9,8-8.5c0.5-4.1-1.9-8.4-5.7-9.9c-1.4-0.6-3-0.8-4.5-0.8
                        c-4.4-0.1-8.8,0-13.2,0c-0.5,0-1,0.1-1.4,0.1c-0.2,0.4-0.4,0.6-0.4,0.8c0,5.7-0.1,11.5-0.1,17.2
                        C106.2,692.6,106.4,692.9,106.6,693.6z M106.5,667.9c0.1,0.1,0.2,0.2,0.3,0.2c5.4,0,10.8,0.1,16.2,0c1.6,0,3-0.8,4.1-1.9
                        c2.8-2.5,3.5-5.6,2.5-9c-0.9-3.4-3.3-5.4-6.8-6c-0.8-0.1-1.5-0.2-2.3-0.2c-4.1,0-8.2,0-12.2,0c-0.6,0-1.2,0.2-1.8,0.2
                        C106.1,654.5,106.1,665.4,106.5,667.9z"/>
                    <path class="path" d="M448.6,750.2c4.8,0,9,0,13.2,0c0.7,1.5,0.3,2.9,0.4,4.3c0.1,1.4,0,2.9,0,4.4c-0.6,0.1-1.1,0.3-1.6,0.3
                        c-10.1,0-20.3,0-30.4,0c-0.3,0-0.6-0.1-0.9-0.1c-0.5-0.9,0.3-1.3,0.6-1.8c4.8-6.2,9.7-12.3,14.5-18.5c1.7-2.2,3.3-4.4,4.8-6.7
                        c0.9-1.4,1.5-2.9,2-4.5c0.3-1.1,0.5-2.4,0.3-3.6c-0.7-4.4-5.1-6.2-8.8-4.8c-1.2,0.5-2,1.4-2.4,2.6c-0.4,1.2-0.8,2.5-1.1,3.8
                        c-0.2,0.7-0.2,1.5-0.3,2.4c-3.5,0.3-6.9,0.1-10.5,0.2c0-1-0.1-1.8-0.1-2.7c0.6-7.4,5-12.9,12-14.9c3.7-1.1,7.4-1.1,11.1-0.1
                        c7.8,2.1,12.2,9.5,10.5,17.4c-0.7,3.5-2.2,6.7-4.2,9.6c-2.4,3.5-4.8,6.8-7.2,10.3C449.9,748.5,449.5,749,448.6,750.2z"/>
                    <path class="path" d="M506,672.5c0.4,13.3-10.4,27.8-27.7,27.8c-15.8,0-27.8-13.2-27.7-27.9c0.1-15.2,12.9-27.9,27.8-27.8
                        C495,644.6,506.4,658.7,506,672.5z M456.6,672.4c-0.1,11.2,8.8,21.7,21.8,21.8c11.7,0,21.9-9.2,21.8-21.8
                        c-0.1-14.1-11.9-21.9-21.9-21.8C466.9,650.6,456.5,659.8,456.6,672.4z"/>
                    <path class="path" d="M208.5,644.6c15-0.2,27.6,12.3,27.6,27.9c0,15-11.9,27.8-27.8,27.7c-16.2-0.1-27.8-13.7-27.7-27.9
                        C180.7,657.5,193.3,644.3,208.5,644.6z M186.6,672.6c-0.3,9.9,7.7,21.6,22,21.6c12.2,0,21.9-9.9,21.7-22
                        c-0.2-13.6-11.7-21.8-22.1-21.6C196,650.7,186.3,660.9,186.6,672.6z"/>
                    <path class="path" d="M316.1,647.5c-0.6,1.9-1.1,3.5-1.6,5c-3.1-0.7-5.9-1.5-8.8-2c-3.6-0.6-7.2-0.6-10.8,0.3
                        c-2.4,0.6-4.6,1.6-6.4,3.3c-3,2.8-3.5,6.4-1.3,9.8c1.4,2.1,3.2,3.6,5.7,4.1c1.5,0.3,3.1,0.4,4.6,0.6c2.7,0.4,5.5,0.7,8.1,1.4
                        c4.1,1,7.4,3.3,9.7,7c4,6.3,2.4,14.4-3.6,18.9c-3.2,2.4-6.8,3.5-10.7,4c-4.2,0.5-8.4,0-12.5-0.9c-2.8-0.6-5.6-1.1-8.3-2.3
                        c0.2-0.8,0.3-1.6,0.6-2.3c0.2-0.8,0.5-1.6,0.8-2.5c2.1-0.1,3.8,0.6,5.6,1c4.4,1.1,8.9,1.4,13.5,1.1c2.7-0.2,5.2-1,7.4-2.6
                        c3.5-2.6,4.7-7.1,3-10.9c-0.8-1.7-2-2.9-3.6-3.7c-2.3-1.2-4.7-1.9-7.2-2.1c-2.2-0.2-4.4-0.4-6.6-0.7c-5-0.7-8.9-3.1-11.5-7.5
                        c-3.1-5.2-2.4-11.5,1.8-15.8c3.1-3.2,7-4.9,11.3-5.8c5.3-1.2,10.5-0.9,15.7,0.8C312.4,646.2,314.1,646.8,316.1,647.5z"/>
                    <path class="path" d="M408.1,651.4c-1.2,1.5-2.8,2.3-4.3,3.5c-1.4-0.8-2.8-1.5-4.1-2.2c-11.5-5.7-24.9-0.5-29.8,11.1
                        c-6.3,14.7,4.7,29,18.1,30.1c5.2,0.4,9.8-0.9,14.1-3.6c1.1-0.7,2.2-1.5,3.3-2.2c2,1.2,2.5,1.7,4.1,4c-14.7,13.3-34.1,8.8-42.8-4.7
                        c-11.2-17.3-0.3-40.1,19.8-42.8c3.9-0.5,7.7-0.1,11.4,1.2C401.7,647.2,405.2,649.1,408.1,651.4z"/>
                    <path class="path" d="M91.7,718.6c0.2,0.3,0.5,0.5,0.5,0.6c0,13.2,0,26.4,0,39.8c-1.3,0.5-2.6,0.2-4.1,0.3c-0.1-0.9-0.2-1.8-0.2-2.6
                        c0-7.5,0-15,0-22.5c0-0.9,0.2-1.9-0.4-3c-1.1,0.5-1.5,1.4-2.1,2.1c-0.6,0.7-1.1,1.4-1.6,2.1c-0.6,0.8-1.2,1.5-1.9,2.3
                        c-0.6,0.7-1.1,1.4-1.7,2.1c-0.6,0.8-1.2,1.5-1.9,2.3c-0.6,0.7-1.1,1.4-1.7,2.1c-0.6,0.7-1.3,1.5-2.1,2.4c-1.6-1.7-2.9-3.5-4.3-5.1
                        c-1.4-1.7-2.8-3.4-4.1-5.2c-1.4-1.7-2.8-3.4-4.1-5c-1.1,0.2-1,0.9-1,1.6c0,4.4,0,8.8,0,13.2c0,3.5,0,7.1,0,10.6
                        c0,0.9-0.1,1.7-0.1,2.7c-1.3,0-2.5,0-3.6,0c-0.2-0.1-0.3-0.2-0.3-0.2c-0.1-0.1-0.1-0.2-0.1-0.3c0-13-0.1-26-0.1-39
                        c0-0.3,0.1-0.6,0.2-1c0-0.1,0.1-0.1,0.3-0.4c5.7,7,11.3,14.1,17,21.1c1.2-0.5,1.7-1.5,2.3-2.3c4.3-5.3,8.6-10.6,12.9-15.9
                        C90.3,720.3,91,719.5,91.7,718.6z"/>
                    <path class="path" d="M517.2,711.1c4.9,0,9.5,0,14.2,0c0.3,0,0.6,0.1,1,0.2c0.1,0.3,0.3,0.6,0.3,0.9c0,15.3,0,30.6,0,45.9
                        c0,0.3-0.2,0.6-0.3,1.1c-3.3,0.3-6.5,0.1-9.7,0.1c-0.8-1.2-0.5-2.3-0.5-3.4c0-10.8,0-21.6,0-32.4c0-1.1,0-2.2,0-3.3
                        c-2.3-0.9-4.5,0-6.8-0.7C515.8,716.7,516.1,714,517.2,711.1z"/>
                    <path class="path" d="M342.5,718.1c12-0.3,20.8,9.8,20.9,20.7c0.1,10.1-7.7,20.9-20.7,21c-11.8,0.1-20.9-9.5-20.9-20.7
                        C321.8,727,331.9,717.9,342.5,718.1z M326.4,739c-0.3,7.6,6,16.3,16.5,16.3c9.2,0,16.2-7.8,16.2-16.3c0-8.3-6.6-16.5-16.4-16.4
                        C331.7,722.7,326.1,731.8,326.4,739z"/>
                    <path class="path" d="M291.7,742.7c0.9,1.6,2,2.8,3,4.1c1,1.4,2.2,2.8,3.2,4.2c1,1.3,2,2.6,3,4c1,1.3,2.1,2.5,2.9,4.2
                        c-1.9,0-3.5,0-5.3,0c-3.8-5-7.8-10-11.6-15c-2.9,0-5.6,0-8.5,0c-0.4,1.7-0.1,3.4-0.2,5c0,1.7,0,3.3,0,5c0,1.6,0.2,3.3-0.2,5
                        c-0.5,0.1-1,0.1-1.4,0.1c-0.8,0-1.5,0-2.1,0c-0.2-0.2-0.3-0.3-0.3-0.4c-0.1-0.1-0.1-0.2-0.1-0.3c0-12.8-0.1-25.6-0.1-38.4
                        c0-0.4,0.1-0.9,0.2-1.3c0-0.1,0.1-0.2,0.3-0.4c4,0,8-0.3,12.1,0.1c8.6,0.6,14,9.1,11.2,17.3c-0.8,2.4-2.1,4.3-4.3,5.7
                        C292.8,741.9,292.3,742.3,291.7,742.7z M278.3,723.1c-0.4,6.4-0.3,13.8,0.3,16.4c2.5,0,5,0,7.5,0c4.5-0.1,7.9-4,8-7.7
                        c0.1-4.5-2.9-8.2-7.4-8.7C283.9,722.8,281.2,723,278.3,723.1z"/>
                    <path class="path" d="M166.6,759.2c-2.2,0-3.8,0-5.5,0c-3.8-5-7.7-9.9-11.6-15c-2.7,0-5.4,0-8.4,0c-0.1,0.6-0.2,1.2-0.2,1.9
                        c0,3.4,0,6.8,0,10.3c0,0.9-0.1,1.7-0.1,2.7c-1.4,0.4-2.7,0.3-4.1,0.1c-0.1-0.6-0.2-1.1-0.2-1.7c-0.3-12.1-0.1-35.7,0.3-38.8
                        c0.6-0.1,1.2-0.2,1.8-0.2c3.2,0,6.4-0.1,9.6,0c5.8,0.2,9.8,3.1,12,8.4c2,4.8,0.6,12.1-4.8,15.1c-0.3,0.2-0.6,0.3-1,0.6
                        c0.3,0.5,0.6,1.1,1,1.6c3,4,6,7.9,9,11.8C165,756.9,165.6,757.8,166.6,759.2z M140.9,739.5c2.8,0,5.2,0.1,7.6,0
                        c4.6-0.2,8.1-3.5,8.2-7.9c0-4.4-3-8.2-7.9-8.6c-2-0.2-4-0.1-5.9,0c-0.6,0-1.3,0.2-1.9,0.2C140.9,728.7,140.9,733.9,140.9,739.5z"/>
                    <path class="path" d="M195.3,723c-6.6,0.2-12.9,0-19.3,0.1c-0.4,3.4-0.3,6.5-0.1,9.8c4.3,0.4,8.5,0,12.6,0.2
                        c0.7,1.4,0.2,2.8,0.4,4.4c-4.4,0.1-8.6,0-12.9,0.1c-0.5,3-0.2,5.9-0.2,8.7c0,2.7-0.1,5.5,0.1,8.3c2,0.3,3.7,0.1,5.5,0.2
                        c1.7,0,3.3,0,5,0c1.8,0,3.5,0,5.3,0c1.6,0,3.3-0.2,5,0.2c0,1.4,0,2.7,0,4c-2.4,0.5-18.8,0.7-25,0.2c-0.1-0.6-0.2-1.2-0.2-1.8
                        c0-12.2,0-24.5,0-36.7c0-0.6,0.1-1.3,0.2-1.9c3.8-0.4,21.1-0.3,23.6,0.1C195.5,720.1,195.4,721.4,195.3,723z"/>
                    <path class="path" d="M26.1,718.8c2.8-0.4,20.5-0.5,23.8-0.1c0.1,0.6,0.2,1.2,0.2,1.8c0,0.6,0,1.3,0,2.1c-0.8,0.1-1.4,0.3-2,0.3
                        c-4.6,0-9.3,0-13.9,0c-1.1,0-2.2,0-3.4,0c-0.7,3.3-0.1,6.4-0.4,9.8c0.8,0.1,1.5,0.2,2.1,0.2c2.9,0,5.7,0,8.6,0
                        c0.8,0,1.5,0.1,2.3,0.1c0.5,1.4,0.2,2.7,0.3,4.2c-2.3,0.5-4.5,0.2-6.7,0.3c-2.1,0.1-4.1,0-6.2,0.1c-0.5,2.7-0.6,11.4-0.2,16.8
                        c0.6,0.1,1.2,0.2,1.8,0.2c5.1,0,10.1,0,15.2,0c1.1,0,2.2,0,3.3,0c0.8,1.5,0.5,2.9,0.3,4c-0.3,0.3-0.3,0.4-0.4,0.4
                        c-0.1,0.1-0.2,0.1-0.3,0.1c-7.5,0-15,0-22.5,0.1c-0.5,0-1.1-0.1-1.8-0.1c-0.1-0.5-0.3-1-0.3-1.6c0-12.6,0-25.1,0-37.7
                        C25.9,719.7,26,719.3,26.1,718.8z"/>
                    <path class="path" d="M368.8,757.2c-0.3-1.5,0.5-2.5,0.8-3.9c1.8,0.4,3.5,0.7,5.2,1.1c3.5,0.7,7,1.1,10.5,0.4
                        c1.5-0.3,2.9-0.9,4.2-1.9c3.6-2.7,3.8-9-1.3-11.1c-2.4-1-4.9-1.2-7.4-1.5c-1.7-0.2-3.5-0.4-5.2-1c-3.6-1.1-7.8-5.5-7.1-11.1
                        c0.2-1.9,1-3.6,2.2-5.1c1.3-1.5,2.9-2.7,4.8-3.5c4.1-1.7,8.4-2.5,12.9-1.5c2.3,0.5,4.5,1.1,6.7,2.1c0.3,1.4-0.6,2.5-0.8,3.8
                        c-2.1-0.5-4-1-5.9-1.4c-3.1-0.6-6.1-0.7-9.2,0.3c-1.1,0.4-2.3,0.8-3.3,1.5c-2.1,1.3-3.5,3.2-3,5.8c0.5,2.5,2,4.4,4.5,5.2
                        c1.3,0.4,2.8,0.5,4.2,0.7c1.7,0.3,3.5,0.4,5.2,0.8c3.1,0.7,5.8,2.2,7.6,4.8c3.5,5,2.5,11.3-2.5,14.9c-2.2,1.6-4.7,2.4-7.4,2.7
                        c-2.8,0.3-5.5,0.2-8.2-0.3C373.8,758.5,371.2,758.1,368.8,757.2z"/>
                    <path class="path" d="M202.7,753.4c3.4,0.6,6.2,1.2,9,1.6c2.4,0.4,4.9,0.4,7.2-0.3c1.4-0.4,2.7-0.9,3.9-1.8
                        c3.9-2.9,3.7-8.9-1.1-11.1c-2.4-1.1-4.9-1.2-7.4-1.6c-1.7-0.2-3.5-0.4-5.2-0.9c-4-1.2-7.7-5.9-7.2-10.7c0.2-2.2,0.9-4.1,2.4-5.6
                        c1.2-1.2,2.6-2.4,4.2-3.1c4.2-2,8.6-2.8,13.2-1.7c1.3,0.3,2.6,0.6,3.8,1c0.9,0.3,1.8,0.7,2.8,1c0.4,1.5-0.5,2.5-0.8,3.9
                        c-2.1-0.5-4-1-5.9-1.4c-3.1-0.6-6.1-0.7-9.2,0.2c-1.1,0.4-2.3,0.8-3.3,1.5c-2.1,1.3-3.5,3.2-3.1,5.8c0.5,2.6,2.1,4.6,4.8,5.4
                        c1.4,0.4,2.8,0.5,4.2,0.6c2.4,0.2,4.8,0.6,7.1,1.5c2.3,0.9,4.2,2.3,5.6,4.4c3.2,4.9,2.3,10.9-2.4,14.4c-2.2,1.7-4.8,2.6-7.6,3
                        c-2.8,0.3-5.5,0.2-8.2-0.3c-2.6-0.5-5.2-1-7.6-1.9C201.7,755.7,202.8,754.8,202.7,753.4z"/>
                    <path class="path" d="M108.4,744.1c0,5.2,0,10,0,14.9c-1.5,0.5-2.7,0.3-3.9,0.2c-0.2-0.2-0.2-0.3-0.3-0.4c-0.1-0.1-0.1-0.2-0.1-0.3
                        c0-12.7-0.1-25.4-0.1-38.1c0-0.5,0.1-1.1,0.1-1.8c0.7-0.1,1.3-0.3,1.9-0.3c3.8,0,7.5-0.1,11.3,0c6.7,0.1,11,4.6,12.2,9.3
                        c2.3,8.6-3.7,16.1-11.7,16.3C114.8,744.2,111.8,744.1,108.4,744.1z M108.5,739.3c0.5,0.1,0.8,0.2,1.1,0.2c2.8,0,5.5,0.1,8.3,0
                        c4.2-0.2,7.5-3.4,7.6-7.7c0.1-3.9-2.1-7.9-7-8.7c-0.8-0.1-1.5-0.1-2.3-0.1c-2.5,0-5,0-7.5,0C108.3,725.7,108.1,733,108.5,739.3z"/>
                    <path class="path" d="M268,758.3c-1.3,0.4-2.3,0.7-3.5,1.1c-0.3-0.5-0.8-1-1-1.6c-1.6-3.5-3.1-7.1-4.6-10.6
                        c-0.4-0.9-0.8-1.8-1.2-2.6c-0.5-0.1-0.8-0.3-1.1-0.3c-3.9,0-7.7,0-11.6,0c-1.6,2.3-2.3,5-3.4,7.5c-1.1,2.5-2.2,5-3.2,7.5
                        c-1.6,0.2-2.7-0.5-4-0.8c0.1-0.5,0-0.8,0.1-1.1c5.4-13.1,10.9-26.2,16.3-39.3c0-0.1,0.2-0.1,0.5-0.2c2.1,4.3,3.8,8.7,5.7,13.1
                        c1.9,4.6,3.8,9.1,5.7,13.7C264.3,749.3,266.4,753.7,268,758.3z M255.4,740.5c0.1-0.3,0.2-0.6,0.1-0.8c-1.4-3.6-2.8-7.1-4.2-10.7
                        c0-0.1-0.1-0.1-0.2-0.2c-0.1,0-0.2,0-0.3,0c-1.8,3.6-3.8,9.2-4.1,11.7c2.5,0,5,0,7.5,0C254.6,740.6,255,740.5,255.4,740.5z"/>
                    <path class="path" d="M312.6,759.2c-1.7,0-2.8,0-4,0c-0.4-2.5-0.5-37.1-0.1-40.5c1.2-0.4,2.5-0.2,3.8-0.1c0.1,0.6,0.2,1,0.2,1.4
                        C312.6,733,312.6,746,312.6,759.2z"/>
                    <path class="path" d="M338.4,343c1.9,1.8,3.5,3.3,5.1,4.8c3.2,3.1,6.4,6.1,10.1,8.6c2.2,1.5,4.5,2.7,6.9,3.9c1.3,0.6,2.7,1,4.1,1.2
                        c4.3,0.7,7.5-1,9.8-4.6c1.7-2.7,2.7-5.8,3.2-9c0.5-3.2,0.9-6.3,1.2-9.5c0.4-4.7-2.3-7.6-6-8.8c-2-0.6-4.1-1.1-6.1-1.3
                        c-6-0.5-11.9,0.1-17.8,1c-1.8,0.3-3.7,0.6-5.9,1c-0.4-0.5-1-1.2-1.5-1.9c-4.1-5.3-8.2-10.6-12.4-15.9c-2.9-3.6-5.3-7.6-7.6-11.6
                        c-15.3-25.9-30.6-51.8-45.9-77.7c-0.5-0.9-1-1.9-1.5-2.7c0.4-0.9,1-0.7,1.5-0.8c7.3-0.9,14.6-2.2,21.6-4.5
                        c9.6-3.2,18.5-7.8,26-14.7c8.3-7.6,14.1-16.9,16.8-27.9c0.4-1.6,0.7-3.2,1.1-4.9c2.7-0.4,5.3-0.1,7.9-0.2c2.8,0,5.5,0,8.3,0
                        c2.6,0,5.3,0,8,0c4-6.2,8-12.4,12-18.5c-0.6-1.1-1.5-0.6-2.2-0.6c-9.7,0-19.4,0-29.1,0c-1.5,0-3.1,0-4.7,0
                        c-0.3-0.6-0.6-1.1-0.7-1.6c-1.6-6.9-4.9-13-9.2-18.5c-0.3-0.3-0.5-0.7-0.8-1.1c-0.1-0.1-0.1-0.2-0.1-0.3c0.4-0.9,1.1-0.5,1.7-0.5
                        c9.9,0.2,19.9,0.4,29.8,0.6c1.1,0,2.2,0,3.4,0c4.3-6.5,8.5-13,12.9-19.7c-0.6-0.2-0.9-0.4-1.2-0.4c-42.8,0-85.6,0-128.5,0
                        c-4.3,6.4-8.6,12.7-12.8,19c-0.1,0.1,0,0.4,0,0.8c0.8,0.2,1.6,0.1,2.5,0.1c10.5,0,21,0,31.4,0c6.4,0,12.8,0.8,18.9,2.7
                        c4.8,1.4,9.3,3.5,13.2,6.6c3.4,2.7,6.3,5.9,8.1,9.9c0.2,0.5,0.4,1,0.6,1.7c-1,0.4-1.8,0.2-2.7,0.3c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0
                        c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0
                        c-0.9,0-1.8,0-2.6,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0
                        c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0c-0.9,0-1.8,0-2.6,0c-1,0-2,0-3,0c-0.9,0-1.8,0-2.8,0c-4.1,6.2-8.2,12.4-12.3,18.6
                        c0.6,0.9,1.3,0.5,1.9,0.6c0.5,0.1,1.1,0,1.7,0c23,0,45.9,0,68.9,0c1.2,0,2.4-0.1,3.7,0.2c0.2,2.3-0.2,4.4-0.7,6.6
                        c-1.7,7.8-5.7,14-12,18.9c-5,3.8-10.6,6.3-16.5,8.1c-10.3,3-20.8,3.8-31.4,3.5c-2.9-0.1-5.9-0.2-9-0.3c0,0.8-0.1,1.4-0.1,2.1
                        c0,4.7,0.1,9.5,0,14.2c0,1.7,0.5,2.9,1.5,4.2c20.3,25.3,40.5,50.6,60.8,76c3.8,4.7,7.6,9.4,11.4,14.2c4.2,5.5,8.4,11.1,12.5,16.7
                        c0.2,0.3,0.3,0.6,0.6,1c-1.7,1-3.6,1-5.3,1.5c-1.7,0.5-3.4,0.8-5.1,1.2c-1.8,0.4-3.6,0.8-5.6,1.2c-0.5-0.6-0.9-1.2-1.3-1.8
                        c-1.6-2.6-3.7-4.6-6.3-6.2c-1.1-0.7-2.2-1.5-3.1-2.4c-6.3-5.7-13-11-20.2-15.5c-5.4-3.3-11-6.2-17.1-7.8c-4.5-1.2-9-1.8-13.7-1.3
                        c-6.9,0.9-12.7,3.8-17.2,9c-6.3,7.4-9.6,16.1-9.5,25.8c0.1,8.3,4,14.5,11.3,18.5c4.3,2.4,9.1,3.4,13.9,3.7c6.5,0.4,13,0,19.5-0.9
                        c9.4-1.3,18.7-3.3,27.9-5.4c0.6-0.1,1.3-0.2,2.1-0.3c0.1,0.8,0.2,1.6,0.3,2.3c0.7,11.6,0.4,23.2,0.2,34.7
                        c-0.3,14.7-0.5,29.3-0.6,44c-0.1,7.5,0.1,15,0.1,22.5c0,1,0,2,0,3.2c-0.8,0.1-1.5,0.3-2.2,0.3c-15.8,0-31.6,0-47.3,0
                        c-4.5,0-7.6-1.9-9.7-5.7c-1.9-3.3-3-6.8-3.4-10.6c-0.5-4.8-1-9.7-1.4-14.5c-0.1-1-0.1-2-0.1-3c-0.1-9.4-1.3-18.7-3-27.9
                        c-4.1-22.3-11.1-43.8-19.1-64.9c-10.3-27-22.5-53.2-35.8-78.8c-3.4-6.7-7-13.2-9.9-20.2c-5.4-12.9-9-26.2-10.8-40.1
                        c-0.4-3.2-0.6-6.4-0.7-9.6c-0.2-5.5-0.5-11-0.3-16.5c1-21.8,6.5-42.4,16.4-61.8c20.1-39.2,56.4-67.8,99.2-78.3
                        c14.3-3.5,28.9-4.8,43.7-4c65,3.5,117.3,47.1,135.9,103.7c3.7,11.4,6.1,23,7.1,34.9c0.6,7.3,0.4,14.5,0.1,21.8
                        c-1.1,23.7-8,45.7-19.2,66.4c-16.9,31.5-31.8,63.9-43.6,97.7c-5.1,14.7-9.5,29.6-12.6,44.8c-2,9.8-3.4,19.8-3.9,29.8
                        c-0.3,5.8-0.9,11.6-1.4,17.5c-0.1,1.3-0.3,2.6-0.4,4c-0.2,3.4-1.3,6.5-2.9,9.4c-2.1,3.9-5.4,5.9-9.9,5.9c-9.7-0.1-19.4,0-29.1,0
                        c-5.5,0-11,0-16.6,0c-0.9,0-1.7-0.1-2.7-0.2c-0.1-1.2-0.1-2.3-0.2-3.4c-0.1-16.3-0.1-32.7-0.3-49c-0.3-15.9-0.8-31.8-1.3-47.6
                        c-0.1-2.8-0.3-5.5-0.5-8.3c0-0.6,0-1.3,0-2.1C322.1,346.6,330.3,344.8,338.4,343z"/>
                    <path class="path" d="M299.8,340c-4.6,1.1-8.6,2-12.6,2.8c-7,1.5-14,2.9-21.2,3.7c-5.6,0.6-11.2,1.2-16.8,0.4
                        c-2.2-0.3-4.3-0.8-6.4-1.7c-4.3-2-6.5-5.2-6.2-10.3c0.3-5.5,2.2-10.6,5.4-15.1c4.2-5.8,10-7.6,16.9-6.5c3.6,0.6,7,1.8,10.3,3.4
                        c5.5,2.6,10.6,5.9,15.4,9.6c4.1,3.2,8.3,6.3,11.7,10.2C297.3,337.6,298.6,338.3,299.8,340z"/>
                    <path class="path" d="M365,349.6c-4.4-2-9.2-5.6-11.7-8.8c3.3-1.2,10.1-1.5,13.5-0.5C366.9,343.4,366.3,346.5,365,349.6z"/>
                    <path class="path" d="M307.6,516.3c-13.8,0-27.6,0-41.4,0c-1,0-2,0.1-3,0c-4.4-0.5-7.6-4-7.6-8.2c0-4.2,3.3-7.7,7.7-8.1
                        c0.8-0.1,1.5,0,2.3,0c27.8,0,55.6,0,83.4,0c1.4,0,2.9,0.1,4.2,0.5c3.6,1,5.8,4.2,5.7,7.9c-0.1,3.6-2.3,6.6-5.9,7.5
                        c-1.3,0.3-2.6,0.4-3.9,0.4C335.4,516.3,321.5,516.3,307.6,516.3z"/>
                    <path class="path" d="M297,548.8c-10,0-20,0-30.1,0c-1.3,0-2.7-0.1-3.9-0.4c-3.6-1-5.9-4.3-5.9-7.9c0.1-3.6,2.5-6.8,6.1-7.7
                        c1.1-0.3,2.2-0.4,3.3-0.4c20.4,0,40.8,0,61.1,0c1,0,2,0.1,2.9,0.3c3.9,0.9,6.5,4.3,6.3,8.2c-0.2,4-3.2,7.3-7.2,7.8
                        c-1,0.1-2,0.1-3,0.1C316.8,548.8,306.9,548.8,297,548.8z"/>
                    <path class="path" d="M568.4,738.3c3.3,0,6.1,2.8,6.1,6.1c0,3.4-2.6,6.2-5.9,6.4c-2.8,0.2-6.1-2.7-6.1-6.1
                        C562.6,740.9,565.6,738.3,568.4,738.3z"/>
                    <path class="path" d="M573.6,724.4c-0.1,2.7-2.5,4.8-5.3,4.7c-2.7-0.1-4.9-2.4-4.8-5.2c0.1-2.8,2.3-5,5.1-4.9
                        C571.5,719.1,573.7,721.4,573.6,724.4z"/>
                    <path class="path" d="M477.4,735.1c-0.1-3,0.3-5.9,1.3-8.8c0.6-1.7,1.4-3.2,2.7-4.5c2.9-2.9,7.2-2.8,9.9,0.3
                        c1.9,2.1,2.7,4.8,3.2,7.5c0.6,3.6,0.7,7.2,0.1,10.9c-0.4,2.2-1,4.3-2.2,6.2c-3.2,5.1-9.1,5.2-12.4,0.1c-1.7-2.7-2.3-5.7-2.6-8.8
                        C477.4,737,477.4,736,477.4,735.1z"/>
                    <path class="path" d="M106.6,693.6c-0.2-0.7-0.3-1-0.3-1.3c0-5.7,0-11.5,0.1-17.2c0-0.2,0.2-0.4,0.4-0.8c0.4,0,0.9-0.1,1.4-0.1
                        c4.4,0,8.8-0.1,13.2,0c1.5,0,3.1,0.3,4.5,0.8c3.8,1.5,6.2,5.9,5.7,9.9c-0.6,4.6-3.8,8-8,8.5c-0.4,0.1-0.9,0.1-1.3,0.1
                        C117.1,693.6,111.9,693.6,106.6,693.6z"/>
                    <path class="path" d="M106.5,667.9c-0.4-2.5-0.4-13.4,0-16.6c0.6-0.1,1.2-0.2,1.8-0.2c4.1,0,8.2,0,12.2,0c0.8,0,1.5,0,2.3,0.2
                        c3.5,0.6,5.9,2.6,6.8,6c0.9,3.4,0.3,6.6-2.5,9c-1.2,1-2.5,1.9-4.1,1.9c-5.4,0-10.8,0-16.2,0C106.7,668,106.6,667.9,106.5,667.9z"/>
                    <path class="path" d="M456.6,672.4c0-12.7,10.3-21.8,21.8-21.9c9.9-0.1,21.8,7.7,21.9,21.8c0.1,12.6-10.2,21.9-21.8,21.8
                        C465.3,694.2,456.4,683.7,456.6,672.4z"/>
                    <path class="path" d="M186.6,672.6c-0.3-11.7,9.3-21.8,21.6-22c10.4-0.1,21.9,8,22.1,21.6c0.2,12.1-9.5,22-21.7,22
                        C194.3,694.2,186.3,682.5,186.6,672.6z"/>
                    <path class="path" d="M326.4,739c-0.3-7.2,5.3-16.4,16.3-16.4c9.8-0.1,16.4,8.1,16.4,16.4c0,8.5-7,16.2-16.2,16.3
                        C332.3,755.3,326.1,746.6,326.4,739z"/>
                    <path class="path" d="M278.3,723.1c2.9-0.1,5.7-0.3,8.4,0c4.4,0.5,7.5,4.2,7.4,8.7c-0.1,3.8-3.5,7.7-8,7.7c-2.5,0-5,0-7.5,0
                        C278,736.9,277.9,729.5,278.3,723.1z"/>
                    <path class="path" d="M140.9,739.5c0-5.6,0-10.8,0-16.2c0.7-0.1,1.3-0.2,1.9-0.2c2,0,4-0.1,5.9,0c4.9,0.4,7.9,4.2,7.9,8.6
                        c0,4.3-3.6,7.7-8.2,7.9C146.1,739.6,143.7,739.5,140.9,739.5z"/>
                    <path class="path" d="M108.5,739.3c-0.4-6.3-0.2-13.6,0.3-16.2c2.5-0.1,5,0,7.5,0c0.8,0,1.6,0,2.3,0.1c4.9,0.8,7.1,4.9,7,8.7
                        c-0.1,4.2-3.4,7.5-7.6,7.7c-2.8,0.1-5.5,0-8.3,0C109.3,739.5,109,739.4,108.5,739.3z"/>
                    <path class="path" d="M255.4,740.5c-0.4,0-0.8,0.1-1.2,0.1c-2.5,0-5,0-7.5,0c0.3-2.5,2.3-8.1,4.1-11.7c0.1,0,0.2,0,0.3,0
                        c0.1,0,0.2,0.1,0.2,0.2c1.4,3.5,2.8,7.1,4.2,10.7C255.6,739.9,255.5,740.1,255.4,740.5z"/>
                </g>
            </svg>
        </div>
    </div>
    <!-- SVG Preloader Ends -->
    <!-- Wrapper Starts -->
    <div class="wrapper">
<!-- Header Starts -->
        <!-- Header Starts -->
        <header class="header">
            <div class="container">
                <div class="row">
                    <!-- Logo Starts -->
                    <div class="main-logo col-xs-12 col-md-3 col-md-2 col-lg-2 hidden-xs">
                        <a href="index.php">
							<img id="logo" class="img-responsive" src="images/logo-dark.png" alt="logo">
						</a>
                    </div>
                    <!-- Logo Ends -->
                    <!-- Statistics Starts -->
                    <div class="col-md-7 col-lg-7">
                        <marquee><ul class="unstyled bitcoin-stats text-center">

                                <?php
                                $host="localhost";
                                $user="boscofes_bemp";
                                $pass="FatherJohnBoscoBoscoFest2018";
                                $db="boscofes_bemp";

                                 $con=mysqli_connect($host,$user,$pass,$db);
                                 if (mysqli_connect_errno())
                                 {
                                    echo "Failed to connect to MySQL: " . mysqli_connect_error();
                                 }                                 
                                 $sql= "SELECT * FROM share_prices";
                                 $result=mysqli_query($con,$sql);
                                 while($row = mysqli_fetch_array($result)){
                                    if($row['curr_price']>$row['prev_price'])
                                        echo "<li><h6 style=\"display: inline-block;\">" . $row['curr_price'] . "</h6><div style=\"display: inline-block; margin-left: 5px\" class=\"arrow-up\"></div><div><span>" . $row['schoolname'] . "</span></div></li>";
                                    else if($row['curr_price']<$row['prev_price'])
                                        echo "<li><h6 style=\"display: inline-block;\">" . $row['curr_price'] . "</h6><div style=\"display: inline-block; margin-left: 5px\" class=\"arrow-down\"></div><div><span>" . $row['schoolname'] . "</span></div></li>";
                                    else
                                        echo "<li><h6 style=\"display: inline-block;\">" . $row['curr_price'] . "</h6><div style=\"display: inline-block; margin-left: 5px\" class=\"arrow-no-change\"></div><div><span>" . $row['schoolname'] . "</span></div></li>";
                                }
                                  

                            ?>
                        </ul></marquee>
                    </div>
                    <!-- Statistics Ends -->
                    <!-- User Sign In/Sign Up Starts -->
                    <div class="col-md-3 col-lg-3">
                        <ul class="unstyled user">
                            <li class="sign-in"><a href="shares.php" class="btn btn-primary">Stock Exchange</a></li>
                        </ul>
                    </div>
                    <!-- User Sign In/Sign Up Ends -->
                </div>
            </div>
            <!-- Navigation Menu Starts -->
            <nav class="site-navigation navigation" id="site-navigation">
                <div class="container">
                    <div class="site-nav-inner">
                        <!-- Logo For ONLY Mobile display Starts -->
                        <a class="logo-mobile" href="index.php">
							<img id="logo-mobile" class="img-responsive" src="images/logo-dark.png" alt="">
						</a>
                        <!-- Logo For ONLY Mobile display Ends -->
                        <!-- Toggle Icon for Mobile Starts -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
                        <!-- Toggle Icon for Mobile Ends -->
                        <div class="collapse navbar-collapse navbar-responsive-collapse">
                            <!-- Main Menu Starts -->
                            <ul class="nav navbar-nav">
                                <li><a href="index.php">Home</a></li>
                                <li class="active"><a href="events.php">Events</a></li>
                                <li><a href="schedule.php">Schedule</a></li> 
                                <li><a href="login.php">Login</a></li>                                 
                                <li><a href="team.php">Our Team</a></li>
                                <li><a href="contact.php">Contact Us</a></li>

                            </ul>
                            <!-- Main Menu Ends -->
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navigation Menu Ends -->
        </header>
        <!-- Header Ends -->
		<!-- Banner Area Starts -->
		<section class="banner-area">
			<div class="banner-overlay">
				<div class="banner-text text-center">
					<div class="container">
						<!-- Section Title Starts -->
						<div class="row text-center">
							<div class="col-xs-12">
								<!-- Title Starts -->
								<h2 class="title-head">Bosco <span><?php echo $event; ?></span></h2>
								<!-- Title Ends -->
								<hr>								
							</div>
						</div>
						<!-- Section Title Ends -->
					</div>
				</div>
			</div>
		</section>
		<!-- Banner Area Starts -->
        <!-- About Section Starts -->
        <section class="about-page">
            <div class="container">
				<!-- Section Content Starts -->
                <div class="row about-content">
                    <!-- Image Ends -->
                    <!-- Content Starts -->
                    <div>
						<div class="feature-about">							
							<p style="color: white; font-size:20px"><?php echo $rules; ?></p>
						</div>						
						<a class="btn btn-primary btn-services" href="events.php">Back</a>
                    </div>
                    <!-- Content Ends -->
					
                </div>
                <!-- Section Content Ends -->
			</div><!--/ Content row end -->
        </section>
        <!-- About Section Ends -->
        <footer class="footer">            
            <!-- Footer Top Area Ends -->
            <!-- Footer Bottom Area Starts -->
            <div class="bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <!-- Copyright Text Starts -->
                            <p class="text-center">Copyright © 2018 Don Bosco School Park Circus</p>
                            <!-- Copyright Text Ends -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer Bottom Area Ends -->
        </footer>
        <!-- Footer Ends -->
		<!-- Back To Top Starts  -->
        <a href="#" id="back-to-top" class="back-to-top fa fa-arrow-up"></a>
		<!-- Back To Top Ends  -->
		
        <!-- Template JS Files -->
        <script src="js/jquery-2.2.4.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/select2.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/custom.js"></script>
		
		<!-- Live Style Switcher JS File - only demo -->
		<script src="js/styleswitcher.js"></script>

    </div>
    <!-- Wrapper Ends -->
</body>

</html>